apiVersion: monitoring.coreos.com/v1
kind: PodMonitor
metadata:
  name: arc-podmonitor
  labels:
    release: kube-prometheus-stack  
spec:
  namespaceSelector:
    matchNames:
      - cmdo-arc-systems 
  selector:
    matchLabels:
      app.kubernetes.io/instance: arc
  podMetricsEndpoints:
    - path: /metrics
      port: metrics 
      interval: 30s
